# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build and set up libzip
      run: |
        mkdir libzip
        cd libzip
        wget https://libzip.org/download/libzip-1.7.3.tar.gz
        tar -xzvf libzip-1.7.3.tar.gz
        cd libzip-1.7.3
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
        make
        make install

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=~/.local ..
        make
        ./test
        ./test_cont_save

    - name: npz check
      run: shasum -c ../test.hash
      working-directory: ./build
